version: '3.8'

services:
  api-server:
    build:
      context: ./api-server
    container_name: api-server
    environment:
      - NODE_ENV=production
      - NATS_URL=nats://nats:4222
      - MONGO_URI=mongodb://mongo:27017/cryptodb
    depends_on:
      - mongo
      - nats
    networks:
      - app-network

  worker-server:
    build:
      context: ./worker-server
    container_name: worker-server
    environment:
      - NODE_ENV=production
      - NATS_URL=nats://nats:4222
    depends_on:
      - nats
    networks:
      - app-network

  nats:
    image: nats:latest
    container_name: nats
    ports:
      - "4222:4222"
    networks:
      - app-network

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - api-server
    networks:
      - app-network

volumes:
  mongo-data:

networks:
  app-network:
    driver: bridge
